/**
 * parity.test.ts — byte-for-byte comparison of TS-baked .bin vs Python-baked
 * reference .bin.
 *
 * The reference .bin is generated by:
 *   python -m host.production.svg_to_packets pipeline/data/test_circle.svg \
 *     --out web/production/tests/test_circle_knife_ref.bin
 *
 * using default config (KNIFE profile, default machine, default quality).
 * The TS side bakes with defaultConfig().machine, KNIFE, qualityConfig() —
 * the same inputs. A passing test means the entire TS pipeline (stages 1-8
 * + wire packet packer) produces byte-identical output to the Python
 * pipeline.
 *
 * On mismatch, the diagnostic decodes the first divergent packet and prints
 * a field-level diff so we can pinpoint which stage diverged.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { bakeBin } from "./svgToPackets.js";
import { defaultConfig, KNIFE, qualityConfig } from "../config/config.js";
import {
    decodePacket,
    FRAMED_PACKET_SIZE,
    FRAME_PREFIX_SIZE,
} from "../wire/src/packet.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = join(__dirname, "..", "..", "pipeline", "data");
const REF = join(__dirname, "tests");

function svg(name: string): string {
    return readFileSync(join(DATA, name), "utf-8");
}

function refBin(name: string): Uint8Array {
    return new Uint8Array(readFileSync(join(REF, name)));
}

/** Find the first byte offset where the two buffers differ, or -1 if identical. */
function firstDiffOffset(a: Uint8Array, b: Uint8Array): number {
    const len = Math.min(a.length, b.length);
    for (let i = 0; i < len; i++) {
        if (a[i] !== b[i]) return i;
    }
    return a.length === b.length ? -1 : len;
}

/** Decode the packet containing byte `off` and print a field-level diff. */
function diffPacketAtByte(tsBin: Uint8Array, refBin: Uint8Array, byteOff: number): string {
    // which framed packet contains this byte?
    const pktIdx = Math.floor(byteOff / FRAMED_PACKET_SIZE);
    const pktStart = pktIdx * FRAMED_PACKET_SIZE + FRAME_PREFIX_SIZE;
    const lines: string[] = [];
    lines.push(`  first diff at byte ${byteOff} (packet #${pktIdx})`);

    if (pktStart + 26 <= tsBin.length && pktStart + 26 <= refBin.length) {
        const ts = decodePacket(tsBin, pktStart);
        const ref = decodePacket(refBin, pktStart);
        const fields: [string, number, number][] = [
            ["magic", ts.magic, ref.magic],
            ["dx", ts.dx, ref.dx],
            ["dy", ts.dy, ref.dy],
            ["dz", ts.dz, ref.dz],
            ["da", ts.da, ref.da],
            ["interval", ts.interval, ref.interval],
            ["flags", ts.flags, ref.flags],
            ["seq", ts.seq, ref.seq],
            ["crc", ts.crc, ref.crc],
        ];
        for (const [name, tsv, refv] of fields) {
            const mark = tsv === refv ? "  " : "!!";
            lines.push(`    ${mark} ${name.padEnd(9)} ts=${tsv}  ref=${refv}`);
        }
    }
    return lines.join("\n");
}

describe("parity: TS bake vs Python reference .bin", () => {
    it("test_circle.svg + KNIFE — byte-for-byte identical", () => {
        const tsBin = bakeBin(
            svg("test_circle.svg"),
            defaultConfig().machine,
            KNIFE,
            qualityConfig(),
        );
        const ref = refBin("test_circle_knife_ref.bin");

        if (tsBin.length !== ref.length) {
            // length mismatch — report packet counts and first diff
            const tsN = Math.floor(tsBin.length / FRAMED_PACKET_SIZE);
            const refN = Math.floor(ref.length / FRAMED_PACKET_SIZE);
            const off = firstDiffOffset(tsBin, ref);
            const diag = off >= 0 ? diffPacketAtByte(tsBin, ref, off) : "(length differs before any byte diff)";
            expect.fail(
                `length mismatch: ts=${tsBin.length} (${tsN} pkts) vs ref=${ref.length} (${refN} pkts)\n${diag}`,
            );
        }

        const off = firstDiffOffset(tsBin, ref);
        if (off >= 0) {
            const diag = diffPacketAtByte(tsBin, ref, off);
            expect.fail(`first byte diff at offset ${off}:\n${diag}`);
        }

        // exact equality — the only assertion that matters
        expect([...tsBin]).toEqual([...ref]);
    });
});
