/**
 * cppRefFixtures.test.ts — real SVG geometry, exported for the C++ CONTRACT tests.
 *
 * Unlike the cppRef*.test.ts generators next to it, this file carries no
 * expected OUTPUT. It exports INPUT geometry only: the repaired Bezier subpaths
 * of test_snake.svg, after loadSvgMmSubpaths + enforceC1.
 *
 * That distinction is the whole reason it exists. flatten.test.ts and
 * constrain.test.ts each assert their caps against real artwork, and they have
 * to: the synthetic fixtures are smooth by construction, and every cap failure
 * the audit found on real geometry (F1, F7) was a case where the artwork
 * accelerated across a step far harder than any hand-built curve does. Porting
 * those tests without the artwork would port the easy half.
 *
 * The C++ side has no SVG parser and no enforceC1 — both are host-stack, outside
 * the port scope — so the pipeline's front end runs here once and the curves
 * cross as raw IEEE-754. The C++ then flattens and constrains them itself, which
 * is what is under test. Nothing about the answer comes from TypeScript.
 *
 *     GEN_CPP_REF=1 npx vitest run test/port/cppRefFixtures
 */

import { it } from "vitest";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { enforceC1 } from "../../src/toolpath/repair.js";
import { loadSvgMmSubpaths } from "../../src/svg/ingest.js";
import { qualityConfig } from "../../src/machine/index.js";
import type { CubicBezier } from "../../src/toolpath/geometry.js";
import { readFixture } from "../helpers.js";
import { hex } from "./refFormat.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "../../../test/data/svg_fixtures.txt");

it("generates the C++ SVG geometry fixtures", (ctx) => {
    if (process.env.GEN_CPP_REF !== "1") {
        ctx.skip();
        return;
    }

    const q = qualityConfig();
    const lines: string[] = [];

    function emit(name: string, svg: string): void {
        const repaired = loadSvgMmSubpaths(readFixture(svg)).subpaths.map(
            (sp) => enforceC1(sp, { angleTolDeg: q.angleTol, gapTolMm: q.gapTol }).repaired,
        );
        lines.push(`fixture ${name} ${repaired.length}`);
        for (const sp of repaired) {
            lines.push(`subpath ${sp.length}`);
            for (const c of sp) {
                lines.push("c " + ([] as number[]).concat(
                    ...([c.p0, c.p1, c.p2, c.p3] as CubicBezier[keyof CubicBezier][])
                        .map((p) => [p.x, p.y]),
                ).map(hex).join(" "));
            }
        }
        lines.push("end");
    }

    emit("snake", "test_snake.svg");

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(
        OUT,
        "# GENERATED by web/test/port/cppRefFixtures.test.ts — do not edit by hand.\n" +
        "# GEN_CPP_REF=1 npx vitest run test/port/cppRefFixtures\n" +
        "# INPUT GEOMETRY ONLY — no expected outputs live here.\n" +
        lines.join("\n") + "\n",
    );
    // eslint-disable-next-line no-console
    console.log(`wrote ${lines.filter((l) => l.startsWith("c ")).length} curves`);
});
