/**
 * cppRefBezier.test.ts — real BEZIER records, exported for the Pico's check.
 *
 * Every subpath of fish.svg through load, clean, annotate and pack, written as the exact 56
 * bytes the wire carries. test/test_planner/test_bezier.cpp decodes each one
 * and runs checkBezier on it: the host's numbers must pass the Pico's check.
 *
 *     GEN_CPP_REF=1 npx vitest run test/port/cppRefBezier
 */

import { it } from "vitest";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { loadSvgPaths } from "../../src/svg/load.js";
import { cleanSubpath } from "../../src/toolpath/clean.js";
import { annotate } from "../../src/toolpath/annotate.js";
import { packBezier } from "../../src/wire/format/bezier.js";
import { qualityConfig } from "../../src/machine/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SVG = join(HERE, "../production/data/fish.svg");
const OUT = join(HERE, "../../../test/data/bezier_records.txt");

it("generates the C++ BEZIER records", (ctx) => {
    if (process.env.GEN_CPP_REF !== "1") {
        ctx.skip();
        return;
    }

    const svg = readFileSync(SVG, "utf-8");
    const lines: string[] = [];
    const q = qualityConfig();
    for (const subpaths of loadSvgPaths(svg).layers.values()) {
        for (const sp of subpaths) {
            const clean = cleanSubpath(sp, { angleTol: q.angleTol, gapTol: q.gapTol });
            if (!clean) continue;
            for (const b of annotate(clean)) lines.push("r " + Buffer.from(packBezier(b)).toString("hex"));
        }
    }

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(
        OUT,
        "# GENERATED by web/test/port/cppRefBezier.test.ts — do not edit by hand.\n" +
        "# GEN_CPP_REF=1 npx vitest run test/port/cppRefBezier\n" +
        "# fish.svg as BEZIER packets, 56 bytes each.\n" +
        lines.join("\n") + "\n",
    );
    // eslint-disable-next-line no-console
    console.log(`wrote ${lines.length} records`);
});
