// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// uart_tx_9bit //
// ------------ //

#define uart_tx_9bit_wrap_target 0
#define uart_tx_9bit_wrap 6
#define uart_tx_9bit_pio_version 0

static const uint16_t uart_tx_9bit_program_instructions[] = {
            //     .wrap_target
    0xf800, //  0: set    pins, 0         side 1
    0x80a0, //  1: pull   block
    0xe501, //  2: set    pins, 1                [5]
    0xf728, //  3: set    x, 8            side 0 [7]
    0x6001, //  4: out    pins, 1
    0x0644, //  5: jmp    x--, 4                 [6]
    0xbf42, //  6: nop                    side 1 [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_tx_9bit_program = {
    .instructions = uart_tx_9bit_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = uart_tx_9bit_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config uart_tx_9bit_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_tx_9bit_wrap_target, offset + uart_tx_9bit_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
static inline void uart_tx_9bit_program_init(PIO pio, uint sm, uint offset, uint pin_tx, uint pin_de, uint baud) {
    // Configure TX pin
    pio_sm_set_pins_with_mask(pio, sm, 1u << pin_tx, 1u << pin_tx);
    pio_sm_set_pindirs_with_mask(pio, sm, 1u << pin_tx, 1u << pin_tx);
    pio_gpio_init(pio, pin_tx);
    // Configure DE pin (starts LOW)
    pio_sm_set_pins_with_mask(pio, sm, 0, 1u << pin_de);
    pio_sm_set_pindirs_with_mask(pio, sm, 1u << pin_de, 1u << pin_de);
    pio_gpio_init(pio, pin_de);
    pio_sm_config c = uart_tx_9bit_program_get_default_config(offset);
    sm_config_set_out_shift(&c, true, false, 32);
    sm_config_set_out_pins(&c, pin_tx, 1);
    sm_config_set_sideset_pins(&c, pin_tx);
    sm_config_set_set_pins(&c, pin_de, 1); // Map 'set' instructions to the DE pin!
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    float div = (float)clock_get_hz(clk_sys) / (8 * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

// ------------ //
// uart_rx_9bit //
// ------------ //

#define uart_rx_9bit_wrap_target 0
#define uart_rx_9bit_wrap 8
#define uart_rx_9bit_pio_version 0

static const uint16_t uart_rx_9bit_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea28, //  1: set    x, 8                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0x00c8, //  4: jmp    pin, 8
    0xc014, //  5: irq    nowait 4 rel
    0x20a0, //  6: wait   1 pin, 0
    0x0000, //  7: jmp    0
    0x8020, //  8: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_rx_9bit_program = {
    .instructions = uart_rx_9bit_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = uart_rx_9bit_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config uart_rx_9bit_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_rx_9bit_wrap_target, offset + uart_rx_9bit_wrap);
    return c;
}

static inline void uart_rx_9bit_program_init(PIO pio, uint sm, uint offset, uint pin_rx, uint baud) {
    pio_sm_set_consecutive_pindirs(pio, sm, pin_rx, 1, false);
    pio_gpio_init(pio, pin_rx);
    gpio_pull_up(pin_rx);
    pio_sm_config c = uart_rx_9bit_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin_rx);
    sm_config_set_jmp_pin(&c, pin_rx);
    sm_config_set_in_shift(&c, true, false, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    float div = (float)clock_get_hz(clk_sys) / (8 * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

